spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/alipay?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet.allow: true
server:
  port: 9090

mybatis:
  type-aliases-package: com.xe.alipay.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.xe.alipay.util.MllMapper
  not-empty: false
  identity: MYSQL
  ORDER: BEFORE


