package com.xe.alipay.mapper;

import com.xe.alipay.model.SysUserPrivilege;
import com.xe.alipay.model.SysUserPrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserPrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_privilege
     *
     * @mbg.generated
     */
    long countByExample(SysUserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_privilege
     *
     * @mbg.generated
     */
    int deleteByExample(SysUserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_privilege
     *
     * @mbg.generated
     */
    int insert(SysUserPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_privilege
     *
     * @mbg.generated
     */
    int insertSelective(SysUserPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_privilege
     *
     * @mbg.generated
     */
    List<SysUserPrivilege> selectByExample(SysUserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_privilege
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysUserPrivilege record, @Param("example") SysUserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_privilege
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysUserPrivilege record, @Param("example") SysUserPrivilegeExample example);
}